import = [
    "~/.config/alacritty/themes/themes/omni.toml"
]

[colors.primary]
background = '#000000'

[font]
size = 12

[selection]
save_to_clipboard = true

[terminal]
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = true
bindings = [
    { mouse = "Right", action = "Paste" },
]

[keyboard]
bindings = [
    { key = "V", mods = "Control", action = "Paste" },
]
